import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:uc_event_hubb/model/quiz.dart';
import 'package:uc_event_hubb/model/event.dart';
import 'package:uc_event_hubb/viewmodel/event_viewmodel.dart';
import 'package:uc_event_hubb/view/widgets/bottom_bar.dart';
import 'package:uc_event_hubb/view/widgets/upcoming_events_section.dart';
import 'package:uc_event_hubb/viewmodel/auth_viewmodel.dart';
import 'package:uc_event_hubb/data/service/cloudinary_service.dart';
import 'dart:io';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'dart:html' as html;
import 'package:firebase_database/firebase_database.dart';
import 'package:image_picker/image_picker.dart';
import 'package:uc_event_hubb/viewmodel/user_viewmodel.dart';

part 'explore_screen_view.dart';
part 'my_ticket_view.dart';
part 'profile_screen_view.dart';
part 'splash_screen_view.dart';
part 'welcoming_page_view.dart';
part 'welcome_page_view.dart';
part 'login_page_view.dart';
part 'registration_page_view.dart';
part 'create_event_view.dart';
part 'event_detail_view.dart';
part 'payment_bottom_sheet.dart';
part 'ticket_detail_view.dart';
