// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXmaTszznwtkIknWuc42MoNeaT3M-O2II',
    appId: '1:763713886510:web:61df0403df8e20014202bf',
    messagingSenderId: '763713886510',
    projectId: 'uceventhub-d3ab6',
    authDomain: 'uceventhub-d3ab6.firebaseapp.com',
    databaseURL: 'https://uceventhub-d3ab6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uceventhub-d3ab6.firebasestorage.app',
    measurementId: 'G-MN4P4LHD8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtHZ6Vyre9xKakBCU8jex3YA1D6_oks0s',
    appId: '1:763713886510:android:ab43719dab8906c84202bf',
    messagingSenderId: '763713886510',
    projectId: 'uceventhub-d3ab6',
    databaseURL: 'https://uceventhub-d3ab6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uceventhub-d3ab6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHrkJfnsQjlxJTuYzoEHTvyryYsK_WWus',
    appId: '1:763713886510:ios:60d0a778154746bf4202bf',
    messagingSenderId: '763713886510',
    projectId: 'uceventhub-d3ab6',
    databaseURL: 'https://uceventhub-d3ab6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uceventhub-d3ab6.firebasestorage.app',
    iosBundleId: 'com.example.ucEventHubb',
  );
}
